name: update-dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 🔥 ここをまとめる
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      # URL収集
      - run: python collect_urls.py

      # SSLチェック
      - run: python scan_ssl.py

      - run: |
          git config user.name bot
          git config user.email bot@bot.com
          git add *.json
          git commit -m "update" || echo "no change"
          git push
